version: "3.8"

services:
  api:
    container_name: user_api
    # restart: always
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    build:
      context: .
    # volumes:
    # - .:/usr/src/app
